# A .sh script needs to be written to wait for database connection to be ready before starting backend service
# currently docker-compose is set to just restart the server on failure which could be resource intensive

FROM node:8.11

RUN npm install -g nodemon