version: '3'

services:
    mysql_db:
        build: ./src/database
        restart: always
        ports:
          - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_USER: ibanuser
            MYSQL_PASSWORD: ibanpassword
            MYSQL_DATABASE: ibanonline
            MYSQL_HOST: localhost

    backend:
        build: ./src/server
        command: npm start
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=development
        volumes:
            - ./src/server:/home/node/app
        ports:
            - "8080:3000"
        restart: on-failure
        depends_on:
            - mysql_db